export const TeamData = [
    {
        id: 1,
        team_name: "49ers",
        x: 10,
        y: 10,
    },
    {
        id: 2,
        team_name: "Rams",
        x: 9,
        y: 10,
    },
    {
        id: 3,
        team_name: "Seahawks",
        x: 8,
        y: 10,
    },
    {
        id: 4,
        team_name: "Cardinals",
        x: 7,
        y: 10,
    },
    {
        id: 5,
        team_name: "Saints",
        x: 6,
        y: 10,
    },
    {
        id: 6,
        team_name: "Panthers",
        x: 5,
        y: 8,
    },
    {
        id: 7,
        team_name: "Buccaneers",
        x: 4,
        y: 8,
    },
    {
        id: 8,
        team_name: "Falcons",
        x: -3,
        y: -5,
    },
    {
        id: 9,
        team_name: "Giants",
        x: 0,
        y: -5,
    },
    {
        id: 10,
        team_name: "Cowboys",
        x: -10,
        y: 5,
    },
    {
        id: 11,
        team_name: "Eagles",
        x: 2,
        y: -7,
    },
    {
        id: 12,
        team_name: "Commanders",
        x: 5,
        y: -5,
    },
    {
        id: 13,
        team_name: "Vikings",
        x: -5,
        y: 5,
    },
    {
        id: 14,
        team_name: "Packers",
        x: 5,
        y: 5,
    },
    {
        id: 15,
        team_name: "Bears",
        x: 8,
        y: 8,
    },
    {
        id: 16,
        team_name: "Lions",
        x: 8,
        y: 8,
    },
    {
        id: 17,
        team_name: "Broncos",
        x: 8,
        y: 8,
    },
    {
        id: 18,
        team_name: "Chiefs",
        x: 8,
        y: -8,
    },
    {
        id: 19,
        team_name: "Raiders",
        x: 8,
        y: -8,
    },
    {
        id: 20,
        team_name: "Chargers",
        x: -8,
        y: 8,
    },
    {
        id: 21,
        team_name: "Colts",
        x: 8,
        y: 4,
    },
    {
        id: 22,
        team_name: "Texans",
        x: 2,
        y: -2,
    },
    {
        id: 23,
        team_name: "Jaguars",
        x: -2,
        y: 2,
    },
    {
        id: 24,
        team_name: "Titans",
        x: -5,
        y: -5,
    },
    {
        id: 25,
        team_name: "Bills",
        x: 1,
        y: -10,
    },
    {
        id: 26,
        team_name: "Dolphins",
        x: -9,
        y: -8,
    },
    {
        id: 27,
        team_name: "Patriots",
        x: -8,
        y: -7,
    },
    {
        id: 28,
        team_name: "Jets",
        x: -10,
        y: 1,
    },
    {
        id: 29,
        team_name: "Browns",
        x: -2,
        y: -8,
    },
    {
        id: 30,
        team_name: "Steelers",
        x: -1,
        y: 2,
    },
    {
        id: 31,
        team_name: "Ravens",
        x: -8,
        y: 7,
    },
    {
        id: 32,
        team_name: "Bengals",
        x: -4,
        y: 8,
    },
];