export const TeamData = [
    {
        id: 1,
        team: "49ers",
        x: 20,
        y: 20,
    },
    {
        id: 2,
        team: "Rams",
        x: 15,
        y: 15,
    },
    {
        id: 3,
        team: "Seahawks",
        x: 10,
        y: 10,
    },
    {
        id: 4,
        team: "Cardinals",
        x: 5,
        y: 5,
    },
    {
        id: 5,
        team: "Saints",
        howGood: 0,
        howLike: 0,
    },
    // {
    //     id: 6,
    //     team: "Panthers",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 7,
    //     team: "Buccaneers",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 8,
    //     team: "Falcons",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 9,
    //     team: "Giants",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 10,
    //     team: "Cowboys",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 11,
    //     team: "Eagles",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 12,
    //     team: "Commanders",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 13,
    //     team: "Vikings",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 14,
    //     team: "Packers",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 15,
    //     team: "Bears",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 16,
    //     team: "Lions",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 17,
    //     team: "Broncos",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 18,
    //     team: "Chiefs",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 19,
    //     team: "Raiders",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 20,
    //     team: "Chargers",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 21,
    //     team: "Colts",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 22,
    //     team: "Texans",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 23,
    //     team: "Jaguars",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 24,
    //     team: "Titans",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 25,
    //     team: "Bills",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 26,
    //     team: "Dolphins",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 27,
    //     team: "Patriots",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 28,
    //     team: "Jets",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 29,
    //     team: "Browns",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 30,
    //     team: "Steelers",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 31,
    //     team: "Ravens",
    //     howGood: 0,
    //     howLike: 0,
    // },
    // {
    //     id: 32,
    //     team: "Bengals",
    //     howGood: 0,
    //     howLike: 0,
    // },
];